services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: health
    volumes:
      - db_data:/var/lib/mysql:Z
    ports:
      - '3306:3306'
      - '33060:33060'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db_data:
